<?php

namespace Laravel\CountryCode\Database\Seeders;

use Illuminate\Database\Seeder;
use Laravel\CountryCode\Models\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            // North America
            [
                'name' => 'United States',
                'iso_alpha2' => 'US',
                'iso_alpha3' => 'USA',
                'iso_numeric' => '840',
                'phone_code' => '1',
                'flag_emoji' => '🇺🇸',
                'continent' => 'North America',
                'region' => 'Northern America',
                'sub_region' => 'North America',
                'capital' => 'Washington, D.C.',
                'currency_code' => 'USD',
                'currency_name' => 'United States Dollar',
                'currency_symbol' => '$',
                'timezone' => 'America/New_York',
                'languages' => ['en'],
                'population' => 331002651,
                'area_km2' => 9833517.0,
                'gdp_usd' => 21433200000000.0,
                'internet_tld' => '.us',
                'driving_side' => 'right',
                'calling_code' => '1',
                'postal_code_format' => '#####-####',
                'postal_code_regex' => '^\\d{5}(-\\d{4})?$',
                'geonames_id' => '6252001',
                'fips_code' => 'US',
                'un_member' => true,
                'independent' => true,
                'status' => 'active',
            ],
            [
                'name' => 'Canada',
                'iso_alpha2' => 'CA',
                'iso_alpha3' => 'CAN',
                'iso_numeric' => '124',
                'phone_code' => '1',
                'flag_emoji' => '🇨🇦',
                'continent' => 'North America',
                'region' => 'Northern America',
                'sub_region' => 'North America',
                'capital' => 'Ottawa',
                'currency_code' => 'CAD',
                'currency_name' => 'Canadian Dollar',
                'currency_symbol' => 'C$',
                'timezone' => 'America/Toronto',
                'languages' => ['en', 'fr'],
                'population' => 37742154,
                'area_km2' => 9984670.0,
                'gdp_usd' => 1736420000000.0,
                'internet_tld' => '.ca',
                'driving_side' => 'right',
                'calling_code' => '1',
                'postal_code_format' => 'A#A #A#',
                'postal_code_regex' => '^[A-Za-z]\\d[A-Za-z] \\d[A-Za-z]\\d$',
                'geonames_id' => '6251999',
                'fips_code' => 'CA',
                'un_member' => true,
                'independent' => true,
                'status' => 'active',
            ],
            [
                'name' => 'Mexico',
                'iso_alpha2' => 'MX',
                'iso_alpha3' => 'MEX',
                'iso_numeric' => '484',
                'phone_code' => '52',
                'flag_emoji' => '🇲🇽',
                'continent' => 'North America',
                'region' => 'Central America',
                'sub_region' => 'North America',
                'capital' => 'Mexico City',
                'currency_code' => 'MXN',
                'currency_name' => 'Mexican Peso',
                'currency_symbol' => '$',
                'timezone' => 'America/Mexico_City',
                'languages' => ['es'],
                'population' => 128932753,
                'area_km2' => 1964375.0,
                'gdp_usd' => 1274440000000.0,
                'internet_tld' => '.mx',
                'driving_side' => 'right',
                'calling_code' => '52',
                'postal_code_format' => '#####',
                'postal_code_regex' => '^\\d{5}$',
                'geonames_id' => '3996063',
                'fips_code' => 'MX',
                'un_member' => true,
                'independent' => true,
                'status' => 'active',
            ],

            // Europe
            [
                'name' => 'United Kingdom',
                'iso_alpha2' => 'GB',
                'iso_alpha3' => 'GBR',
                'iso_numeric' => '826',
                'phone_code' => '44',
                'flag_emoji' => '🇬🇧',
                'continent' => 'Europe',
                'region' => 'Northern Europe',
                'sub_region' => 'Europe',
                'capital' => 'London',
                'currency_code' => 'GBP',
                'currency_name' => 'British Pound',
                'currency_symbol' => '£',
                'timezone' => 'Europe/London',
                'languages' => ['en'],
                'population' => 67886011,
                'area_km2' => 242900.0,
                'gdp_usd' => 2870000000000.0,
                'internet_tld' => '.uk',
                'driving_side' => 'left',
                'calling_code' => '44',
                'postal_code_format' => 'A#A #AA',
                'postal_code_regex' => '^[A-Z]{1,2}\\d[A-Z\\d]? ?\\d[A-Z]{2}$',
                'geonames_id' => '2635167',
                'fips_code' => 'UK',
                'un_member' => true,
                'independent' => true,
                'status' => 'active',
            ],
            [
                'name' => 'Germany',
                'iso_alpha2' => 'DE',
                'iso_alpha3' => 'DEU',
                'iso_numeric' => '276',
                'phone_code' => '49',
                'flag_emoji' => '🇩🇪',
                'continent' => 'Europe',
                'region' => 'Western Europe',
                'sub_region' => 'Europe',
                'capital' => 'Berlin',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'currency_symbol' => '€',
                'timezone' => 'Europe/Berlin',
                'languages' => ['de'],
                'population' => 83783942,
                'area_km2' => 357022.0,
                'gdp_usd' => 4223000000000.0,
                'internet_tld' => '.de',
                'driving_side' => 'right',
                'calling_code' => '49',
                'postal_code_format' => '#####',
                'postal_code_regex' => '^\\d{5}$',
                'geonames_id' => '2921044',
                'fips_code' => 'GM',
                'un_member' => true,
                'independent' => true,
                'status' => 'active',
            ],
            [
                'name' => 'France',
                'iso_alpha2' => 'FR',
                'iso_alpha3' => 'FRA',
                'iso_numeric' => '250',
                'phone_code' => '33',
                'flag_emoji' => '🇫🇷',
                'continent' => 'Europe',
                'region' => 'Western Europe',
                'sub_region' => 'Europe',
                'capital' => 'Paris',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'currency_symbol' => '€',
                'timezone' => 'Europe/Paris',
                'languages' => ['fr'],
                'population' => 65273511,
                'area_km2' => 551695.0,
                'gdp_usd' => 2715000000000.0,
                'internet_tld' => '.fr',
                'driving_side' => 'right',
                'calling_code' => '33',
                'postal_code_format' => '#####',
                'postal_code_regex' => '^\\d{5}$',
                'geonames_id' => '3017382',
                'fips_code' => 'FR',
                'un_member' => true,
                'independent' => true,
                'status' => 'active',
            ],

            // Asia
            [
                'name' => 'China',
                'iso_alpha2' => 'CN',
                'iso_alpha3' => 'CHN',
                'iso_numeric' => '156',
                'phone_code' => '86',
                'flag_emoji' => '🇨🇳',
                'continent' => 'Asia',
                'region' => 'Eastern Asia',
                'sub_region' => 'Asia',
                'capital' => 'Beijing',
                'currency_code' => 'CNY',
                'currency_name' => 'Renminbi',
                'currency_symbol' => '¥',
                'timezone' => 'Asia/Shanghai',
                'languages' => ['zh'],
                'population' => 1439323776,
                'area_km2' => 9596961.0,
                'gdp_usd' => 14342900000000.0,
                'internet_tld' => '.cn',
                'driving_side' => 'right',
                'calling_code' => '86',
                'postal_code_format' => '######',
                'postal_code_regex' => '^\\d{6}$',
                'geonames_id' => '1814991',
                'fips_code' => 'CH',
                'un_member' => true,
                'independent' => true,
                'status' => 'active',
            ],
            [
                'name' => 'India',
                'iso_alpha2' => 'IN',
                'iso_alpha3' => 'IND',
                'iso_numeric' => '356',
                'phone_code' => '91',
                'flag_emoji' => '🇮🇳',
                'continent' => 'Asia',
                'region' => 'Southern Asia',
                'sub_region' => 'Asia',
                'capital' => 'New Delhi',
                'currency_code' => 'INR',
                'currency_name' => 'Indian Rupee',
                'currency_symbol' => '₹',
                'timezone' => 'Asia/Kolkata',
                'languages' => ['hi', 'en'],
                'population' => 1380004385,
                'area_km2' => 3287263.0,
                'gdp_usd' => 2875000000000.0,
                'internet_tld' => '.in',
                'driving_side' => 'left',
                'calling_code' => '91',
                'postal_code_format' => '######',
                'postal_code_regex' => '^\\d{6}$',
                'geonames_id' => '1269750',
                'fips_code' => 'IN',
                'un_member' => true,
                'independent' => true,
                'status' => 'active',
            ],
            [
                'name' => 'Japan',
                'iso_alpha2' => 'JP',
                'iso_alpha3' => 'JPN',
                'iso_numeric' => '392',
                'phone_code' => '81',
                'flag_emoji' => '🇯🇵',
                'continent' => 'Asia',
                'region' => 'Eastern Asia',
                'sub_region' => 'Asia',
                'capital' => 'Tokyo',
                'currency_code' => 'JPY',
                'currency_name' => 'Yen',
                'currency_symbol' => '¥',
                'timezone' => 'Asia/Tokyo',
                'languages' => ['ja'],
                'population' => 126476461,
                'area_km2' => 377975.0,
                'gdp_usd' => 5081770000000.0,
                'internet_tld' => '.jp',
                'driving_side' => 'left',
                'calling_code' => '81',
                'postal_code_format' => '###-####',
                'postal_code_regex' => '^\\d{3}-\\d{4}$',
                'geonames_id' => '1861060',
                'fips_code' => 'JA',
                'un_member' => true,
                'independent' => true,
                'status' => 'active',
            ],

            // Add more countries here...
        ];

        foreach ($countries as $country) {
            Country::updateOrCreate(
                ['iso_alpha2' => $country['iso_alpha2']],
                $country
            );
        }
    }
} 